### ISSUE TITLE
Execution difference between web ui and cli

### ISSUE THREAD

**Issue by lat0z** [yohamta/dagu#168]
I am currently testing the execution of a workflow created from the web ui, with the examples/minimal.yaml content.
From the start button I get an error "exec: no command".
From ./dagu start /home/minimal.yaml there are no errors. 
Am I missing any extra configuration?
This is the content of my admin.yaml 
```host: 0.0.0.0
port: 8080
dags: /home/
isBasicAuth: true
basicAuthUsername: admin
basicAuthPassword: admin
```

**Comment by yohamta** [comment]
@lat0z Thank you very much for reporting the issue; it has been fixed in `v1.13.15`.
