### ISSUE TITLE
Allow `parameters` field contains spaces inside each parameter wrapped by quotes

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#214]

**Comment by Arvintian** [comment]
Can use https://github.com/mattn/go-shellwords to parse parameters?

**Comment by yohamta** [comment]
Thanks for that! I think it's perfect for parsing parameters :)

**Comment by yohamta** [comment]
@Arvintian I will try to fix this using the library today :)

**Comment by yohamta** [comment]
@Arvintian It worked ! Thanks :)
