### ISSUE TITLE
Add an optional parameter `--config` for all sub commands

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#216]
Why: this makes it easier to run multiple Dagu servers on a single instance.

**Comment by Arvintian** [comment]
Should merge [admin-configuration](https://github.com/yohamta/dagu#admin-configuration), env、admin config、global config into one config file, and the config file can specify by --config?

I think this way is clearer to config server or scheduler and easy to organize multiple instances's data.

**Comment by Arvintian** [comment]
By the way, we can remove the rely of the $HOME path. Dagu's work dir can specify in the config file.

**Comment by Arvintian** [comment]
Make dagu's execution environment don't rely on some sys environment. It is useful to run dagu on cloud or container platform. User can run dagu multi-instance or multi-tenancy.

https://github.com/yohamta/dagu/discussions/200

**Comment by yohamta** [comment]
Thanks for the great suggestions!

> Should merge [admin-configuration](https://github.com/yohamta/dagu#admin-configuration), env、admin config、global config into one config file, and the config file can specify by --config?
> 
> I think this way is clearer to config server or scheduler and easy to organize multiple instances's data.

I agree 100%. Good idea.

> By the way, we can remove the rely of the $HOME path. Dagu's work dir can specify in the config file.

I was thinking of adding a config `home` and `DAGU__ADMIN_HOME` env similar to `$AIRFLOW_HOME` in [Airflow' config](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html).

**Comment by Arvintian** [comment]
I think config have a single entry is import. Currently admin's config some in admin.yaml, some in env. I am confused about it.
After review code, i found three type config.

- For admin(server&scheduler) config.
- For operator(start/stop...) and dag config.
- For both admin and operator.

It's a little messy now :) and some code is coupling.

My idea:

- env config is base like $AIRFLOW_HOME, just `home` and `database` config eg, for admin and  operator but no business configuration.
- admin config and global config should merge?
- about dag config, it can understand not is config, it is dag object spec, should it is independent.

refer to kubernetes:

> kubectl --kubeconfig ~/.kube/myconfig apply deployment-spec.yaml

dagu can as:

> dagu [start/stop/server] --config mydaguconfig [dag-spec.yaml]

**Comment by yohamta** [comment]
Thanks for sharing the idea!

> I think config have a single entry is important. Currently admin's config some in admin.yaml, some in env. I am confused about it.

Yeah, I utterly agree :) Let's make it to a single entry. I think it's best for env is for only basic config. For now, only `home` env is necessary to find the global config for start/stop commands.

> admin config and global config should merge.

I think they have different purposes: the admin config is for scheduler/server, while the global config is for common settings for all DAGs such as `env` or `mailOn`, which are not necessary for scheduler/server.

How about adding a new admin field `baseConfig` and removing the concept of `global config` as below?

```yaml
baseConfig: <path/to/global config yaml>
```

Other than that, I agree 100% :)

**Comment by Arvintian** [comment]
Follow this pattern:
> dagu --config my-dagu-config [start/stop/server] [dag-spec.yaml]

I think env is for dagu's basic work, link save database、logs、suspend eg. Some default configs value can use default env value to set default value, link data path eg. But it is not use to find config, it is use to dagu self work, like save state、cache eg.

> Only home env is necessary for operator(start/stop/...) commands to find the admin config, for now, I think.

`--config` can tell all components where to find config file. For now default value, can point to default value ($home[~/.dagu]/admin.yaml), this behavior is compatible fallback.

`baseConfig` is a good idea for common settings among all DAGs, it's default value can be ($home[~/.dagu]/config.yaml) for compatible fallback, i agree about it 👍 .

**Comment by yohamta** [comment]
Sounds good, completely agreed 👍 .

**Comment by yohamta** [comment]
done!
