### ISSUE TITLE
Add `host`, `port` arguments for `dagu server` command

### ISSUE THREAD

**Issue by yohamta** [yohamta/dagu#276]
example:
```sh
dagu server --host=somehost --port=8000
```

**Comment by yohamta** [comment]
done

**Comment by pencilcheck** [comment]
does this work for `dagu scheduler` as well??

**Comment by yohamta** [comment]
@pencilcheck No, it does not. The `dagu scheduler` command only executes the scheduler process and does not start the web server, so it does not have the `host` and `port` arguments. dagu scheduler` and `dagu server` must be started separately.

**Comment by pencilcheck** [comment]
got it
