### ISSUE TITLE
Small UI issue on Spec view

### ISSUE THREAD

**Issue by fishnux** [yohamta/dagu#277]
**Minimal reproducible example DAG**
```
steps:
  - name: test1,2
    command: bash test1,2.bash
```

**What happens**
<img width="295" alt="Screenshot" src="https://user-images.githubusercontent.com/29991194/185022051-e0717c54-0907-4392-9e2c-dad2db211969.png">
Number 2 is really big

**Comment by yohamta** [comment]
Thank you very much for reporting :)

It is fixed in the new release `v1.7.6`.
