### ISSUE TITLE
need update version in Dockerfile

### ISSUE THREAD

**Issue by freexmonster** [yohamta/dagu#353]
I spent half a day building the container until I noticed that the release is the old one.
https://github.com/yohamta/dagu/blob/83bda8d16c7a681ceb00be9aa08adb3eec7b93d4/Dockerfile#L5

**Comment by yohamta** [comment]
Thanks for raising the issue, will fix soon!

**Comment by yohamta** [comment]
Added a instruction in the README. Thansk!
