### ISSUE TITLE
add tzdata to Dockerfile

### ISSUE THREAD

**Issue by freexmonster** [yohamta/dagu#354]
https://github.com/yohamta/dagu/blob/83bda8d16c7a681ceb00be9aa08adb3eec7b93d4/Dockerfile#L17
`apk add --no-cache sudo tzdata`

this adds the ability to set timezones in the container via env:
`TZ: 'Europe/Berlin'`

**Comment by yohamta** [comment]
Thanks! Fixed the in the latest docker image (v1.9.1).
