### ISSUE TITLE
where is the web ui codes?

### ISSUE THREAD

**Issue by feitian124** [yohamta/dagu#79]
hello, i can not find the web ui codes, does it open source or not?
thank you.

**Comment by yohamta** [comment]
@feitian124 Hello, thanks for the question! All web UI codes are under this directory. I wrote everything in gotemplate. It would be fantastic if you could create a PR to improve them :)
https://github.com/yohamta/dagu/tree/main/internal/admin/handlers/web/templates

**Comment by feitian124** [comment]
get it. thanks
i thought it is a react app, suprise to see only 3 go template files.

**Comment by yohamta** [comment]
You’re right, it’s React.
